# Generated by Django 4.1.6 on 2023-02-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDCost',
            field=models.IntegerField(blank=True, null=True, verbose_name='product cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDDescription',
            field=models.TextField(max_length=300, verbose_name='product description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDName',
            field=models.CharField(max_length=100, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDPrice',
            field=models.IntegerField(blank=True, null=True, verbose_name='product price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDTime_created',
            field=models.DateTimeField(verbose_name='product created'),
        ),
    ]
