# Generated by Django 4.1.6 on 2023-02-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_accessory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_accessory',
            name='PACCAccessories',
            field=models.ManyToManyField(related_name='Accessory_product', to='product.product', verbose_name='Accessories'),
        ),
        migrations.AlterField(
            model_name='product_accessory',
            name='PACCProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mainAccessory_product', to='product.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALTAlternatives',
            field=models.ManyToManyField(related_name='alternative_product', to='product.product', verbose_name='Alternatives'),
        ),
        migrations.AlterField(
            model_name='product_alternative',
            name='PALTProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_product', to='product.product', verbose_name='Product'),
        ),
    ]
