# Generated by Django 4.1.6 on 2023-02-19 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_prdimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDDiscountprice',
            field=models.IntegerField(blank=True, null=True, verbose_name='product Discountprice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDImage',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='product/', verbose_name='image'),
        ),
    ]
