# Generated by Django 4.1.6 on 2023-02-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_product_prddiscountprice_alter_product_prdimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='PRDISBestSeller',
            field=models.BooleanField(default=False, verbose_name='product is best_saller'),
        ),
        migrations.AddField(
            model_name='product',
            name='PRDISNew',
            field=models.BooleanField(default=True, verbose_name='product is new'),
        ),
    ]
