# Generated by Django 4.1.6 on 2023-02-22 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_product_prdisbestseller_product_prdisnew'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
