# Generated by Django 4.1.6 on 2023-02-22 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('product', '0015_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='PRDBBrand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.brand', verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDCost',
            field=models.IntegerField(blank=True, null=True, verbose_name='cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDDescription',
            field=models.TextField(max_length=300, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDDiscountprice',
            field=models.IntegerField(blank=True, null=True, verbose_name='Discountprice'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDName',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDPrice',
            field=models.IntegerField(blank=True, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDSlug',
            field=models.SlugField(blank=True, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='product',
            name='PRDTime_created',
            field=models.DateTimeField(verbose_name='created'),
        ),
    ]
